### ISSUE TITLE
I can't find Options / Settings page on Safari

### ISSUE THREAD

**Issue by ikaroz** [james-fray/YouTube-HD#2]
Hi. The FAQ says that is possible change settings on Options page, but I can't find it on Safari. How can I access it?

I'm using Safari 8.0.5 on OS X Yosemite 10.10.3.

**Comment by james-fray** [comment]
Right, there is no options page for Safari yet. The options page is accessible in Firefox, Opera and Chrome version for this release. I'll try to implement in on Safari for next release.

**Comment by joemerlino** [comment]
still not available for safari, @james-fray any update?

**Comment by james-fray** [comment]
Well, the problem is Safari is not providing any useful UI element in its setting page to open the addon's Options page. I was looking for some sort of button element to let user click and access the actual settings page, but there is none available!
https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/ExtensionSettings/ExtensionSettings.html

I can still add a toolbar button just to let use open the Options page, but I personally don't like to declutter  toolbar space for such a rare usage.

**Comment by joemerlino** [comment]
@james-fray do it, users who don't need it can take it off from the toolbar and add it back when/if they need it.

**Comment by james-fray** [comment]
done. There is a new toolbar button to access extension's options page
